version: "3.9"

services:
  backend:
    # .NET 8 API (использует Neon, локальный контейнер Postgres не нужен)
    platform: linux/amd64
    build:
      context: ./AdBoard.API
      dockerfile: Dockerfile
    container_name: adboard-backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_DETAILEDERRORS: "true"
      # строка подключения к Neon берётся из .env
      ConnectionStrings__AdBoardDbConnection: ${NEON_CONNECTION_STRING}
      Security__JwtAccessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
      Security__JwtRefreshTokenKey: ${JWT_REFRESH_TOKEN_KEY}
      Supabase__Url: ${SUPABASE_URL}
      Supabase__Key: ${SUPABASE_KEY}

  frontend:
    # Next.js dev
    platform: linux/amd64
    build:
      context: ./AdBoard.Web
      dockerfile: Dockerfile
    container_name: adboard-frontend
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      # ходим в бэк по имени сервиса внутри docker network
      API_INTERNAL_URL: http://adboard-backend:8080
    volumes:
      - ./AdBoard.Web/src:/app/src
      - ./AdBoard.Web/public:/app/public
      - ./AdBoard.Web/package.json:/app/package.json
      - ./AdBoard.Web/package-lock.json:/app/package-lock.json
